# -*- coding: utf-8 -*-
"""Airplane-code.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18ADCS0oUn8HgBQzvbK2R3rVjpW5cHAXC
"""

class Passenger:
    # Constructor with basic passenger information
    def __init__(self, name, booking_reference):
        self.name = name
        self.booking_reference = booking_reference
        self.seat_preference = None  # It is initialized as None so that it can be written later
        self.meal_preference = None  # It is initialized as None so that it can be written later
        self.boarding_pass = None  # It will be linked to a BoardingPass object later when we define an object therefore it is None.
    #The getter method for the passenger's name
    def get_name(self):
        return self.name
    #The setter method for the passenger's name
    def set_name(self, name):
        self.name = name
    #The getter method for the passenger's booking reference
    def get_booking_reference(self):
        return self.booking_reference
    #The setter method for the passenger's booking reference
    def set_booking_reference(self, booking_reference):
        self.booking_reference = booking_reference
    #The getter method for the passenger's seat preference
    def get_seat_preference(self):
        return self.seat_preference
    #The setter method for the passenger's seat preference
    def set_seat_preference(self, seat_preference):
        self.seat_preference = seat_preference
    #The getter method for the passenger's meal preference
    def get_meal_preference(self):
        return self.meal_preference
    #The setter method for the passenger's meal preference
    def set_meal_preference(self, meal_preference):
        self.meal_preference = meal_preference
    #The getter method for the passenger's boarding pass
    def get_boarding_pass(self):
        return self.boarding_pass
    #The setter method for linking a boarding pass to the passenger
    def set_boarding_pass(self, boarding_pass):
        self.boarding_pass = boarding_pass
# Another class is introduced which is a class that is representing a flight
class Flight:
    # Constructor with the details of the flight
    def __init__(self, flight_number, departure, arrival, date, time):
        self.flight_number = flight_number
        self.departure = departure
        self.arrival = arrival
        self.date = date
        self.time = time
#Another class representing a boarding pass
class BoardingPass:
    # Constructor with the details of the boarding pass
    def __init__(self, passenger, flight, seat, gate, boarding_time, terminal):
        self.passenger = passenger  #This links to the Passenger object
        self.flight = flight        #This links to the Flight object
        self.seat = seat            #This is for assigning a seat for the passenger
        self.gate = gate            #This is about the departure gate for the flight
        self.boarding_time = boarding_time  #It is about the time until which passenger can board
        self.terminal = terminal    #The terminal number at the airport
        self.barcode = "123456" #Placeholder for barcode value as every boarding have a barcode but I wrote it in a general case because in real life it would be different.
#Another Class representing the airline's system
class AirlineSystem:
    # Constructor for the airline system which will manage all objects
    def __init__(self):
        self.passengers = []  #here there is a list to store the passenger objects
        self.flights = []     #Another List to store the Flight objects
#Here we are basically testing the code to see if it works properly and that is when it prints the boarding pass in the figure
# Instantiate objects with sample data from the boarding pass in the figure of assignment descriptions
passenger = Passenger("JAMES SMITH", "5A6BCD78")
flight = Flight("NA4321", "CHICAGO ORD", "NEW YORK JFK", "06 DEC 20", "11:40")
boarding_pass = BoardingPass(passenger, flight, "09A", "03", "11:20", "2")
# Use the objects' functions to display the boarding pass details
print("Boarding Pass Details:")
print(f"Passenger: {passenger.get_name()}")
print(f"From: {flight.departure}")
print(f"To: {flight.arrival}")
print(f"Flight: {flight.flight_number}")
print(f"Date: {flight.date}")
print(f"Time: {flight.time}")
print(f"Gate: {boarding_pass.gate}")
print(f"Boarding till: {boarding_pass.boarding_time}")
print(f"Seat: {boarding_pass.seat}")
print(f"Terminal: {boarding_pass.terminal}")
print(f"Electronic ticket number: {passenger.get_booking_reference()}")
print(f"Barcode: {boarding_pass.barcode}")

